#######################################################################
# Include the common makefiles:
#   - Variables:     Sets up the variables with some default values
-include makefile_utils/common_variables.mk
#######################################################################

# Project Name
PROJECT_NAME = hadamard

# Add your souce directories here
SOURCE_DIRS = \
	. \

#######################################################################
# Include the common makefiles:
#   - shared-lib:     Configuration for shared lib (.so)
#   - var_expansions: Generates lists of source, objects etc
#   - warnings:       Set the warning flags for various targets
#   - targets:        Set the compiler flags for the build target
#   - rules:          The build rules
-include makefile_utils/common_shared_lib.mk
-include makefile_utils/common_var_expansions.mk
-include makefile_utils/common_warnings.mk
-include makefile_utils/common_targets.mk
-include makefile_utils/common_rules.mk
#######################################################################

